larsk21/compiler-minijava

src/main/java/edu/kit/compiler/data/Literal.java, src/main/java/edu/kit/compiler/data/Token.java, src/main/java/edu/kit/compiler/lexer/Lexer.java, src/test/java/edu/kit/compiler/lexer/LexerTest.java
=> Fix lexing of large integer literals

pom.xml, src/main/java/edu/kit/compiler/JavaEasyCompiler.java
=> Disable partial matching in command line parser

run, src/main/java/edu/kit/compiler/JavaEasyCompiler.java, src/main/java/edu/kit/compiler/data/CompilerException.java, src/main/java/edu/kit/compiler/data/FileInputException.java, src/main/java/edu/kit/compiler/io/ReaderCharIterator.java, src/main/java/edu/kit/compiler/lexer/LexException.java, src/main/java/edu/kit/compiler/lexer/Lexer.java, src/main/java/edu/kit/compiler/logger/Logger.java, src/main/java/edu/kit/compiler/parser/ParseException.java, src/test/java/edu/kit/compiler/cmd/LineEndingTestForEcho.java
This PR proposes a unified logging system for our compiler. Please let me know if you would like changes to the overall design or to the API of `Logger`. Console output is currently structured as follows:
```
error: lexer: 42,28: unexpected character '$'
```
=> Proposal for logging system

build
example: `./build -DskipTests`
=> build script: pass arguments to Maven

src/main/java/edu/kit/compiler/data/AstNode.java, src/main/java/edu/kit/compiler/data/AstObject.java, src/main/java/edu/kit/compiler/data/ast_nodes/ClassNode.java, src/main/java/edu/kit/compiler/data/ast_nodes/MethodNode.java, src/main/java/edu/kit/compiler/parser/Parser.java, src/main/java/edu/kit/compiler/parser/PrettyPrintAstVisitor.java, src/test/java/edu/kit/compiler/parser/PrettyPrintAstVisitorTest.java
- add AstObject class
- make AstNode and several AST classes extend AstObject
- pass position to new AstObject classes during parsing
=> add AST object

.gitignore, documents/assignment-04/assignment-04.tex
This is a first (mostly complete) version of Assignment 4 (~[assignment-04.pdf](https://github.com/larsk21/compiler-minijava/files/7528384/assignment-04.pdf)~).
=> Assignment 4 - Abstract syntax and attribute grammar

src/test/java/edu/kit/compiler/cmd/EchoLineEndingTest.java, src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorSystemTest.java, src/test/java/edu/kit/compiler/semantic/SymbolTableTest.java
- rename test classes to fit Maven's naming conventions
- resolve IDE warnings (unused variables)
=> Clean up some tests

.github/workflows/maven.yml, .gitignore, .gitmodules, build, pom.xml, run
=> Integrate libFirm into our compiler

.gitignore, build, lib/stdlib.c, run, src/main/java/edu/kit/compiler/JavaEasyCompiler.java, src/main/java/edu/kit/compiler/transform/Lower.java, src/main/java/edu/kit/compiler/transform/StandardLibraryEntities.java
Standard library methods have been tested in small handmade Firm programs.
=> Implement standard library and code generation

src/main/java/edu/kit/compiler/parser/PrettyPrintAstVisitor.java, src/test/java/edu/kit/compiler/parser/PrettyPrintAstVisitorTest.java
=> Fix pretty printing of negative integer literals

src/main/java/edu/kit/compiler/JavaEasyCompiler.java, src/main/java/edu/kit/compiler/transform/StandardLibraryEntities.java, src/main/java/edu/kit/compiler/transform/TypeMapper.java
- Fix type construction for arrays
- Use jFirm Singleton in the CLI
- Add method for retrieving standard library entities
=> Miscellaneous changes to transform phase

src/main/java/edu/kit/compiler/transform/IRBooleanExpressions.java, src/main/java/edu/kit/compiler/transform/IRExpressionVisitor.java, src/main/java/edu/kit/compiler/transform/IRPointerVisitor.java, src/main/java/edu/kit/compiler/transform/IRStatementVisitor.java, src/main/java/edu/kit/compiler/transform/IRVisitor.java, src/main/java/edu/kit/compiler/transform/Lower.java, src/main/java/edu/kit/compiler/transform/StandardLibraryEntities.java, src/main/java/edu/kit/compiler/transform/TransformContext.java, src/main/java/edu/kit/compiler/transform/TypeMapper.java, src/main/java/edu/kit/compiler/transform/TypedEntity.java, src/test/java/edu/kit/compiler/transform/TypeMapperTest.java
- Finish layout of `ArrayType`s
- Add `getMode(DataType)` method
- Add `TypedEntity<T>` class for methods
=> Improvments to TypeMapper

mjtest-files/compile-firm/IntMax.mj, src/main/java/edu/kit/compiler/transform/IRExpressionVisitor.java
Currently, the conversion to 64 bit is implented only for division
=> Fix IL generation for modulo

src/main/java/edu/kit/compiler/codegen/pattern/LoadMemoryPattern.java, src/main/java/edu/kit/compiler/intermediate_lang/Instruction.java, src/test/java/edu/kit/compiler/intermediate_lang/InstructionTest.java
Also adds an additional check for instruction creation and fixes a missing input register in a memory pattern
=> Ensure that replacing virtual registers works correctly

src/main/java/edu/kit/compiler/lexer/Character.java, src/main/java/edu/kit/compiler/lexer/Lexer.java
Finally fix the regression introduced into the lexer.
=> Lexer Regression

mjtest-files/compile/RegisterClobber.mj, src/main/java/edu/kit/compiler/register_allocation/ApplyAssignment.java, src/main/java/edu/kit/compiler/register_allocation/LifetimeAnalysis.java, src/main/java/edu/kit/compiler/register_allocation/LinearScan.java, src/test/java/edu/kit/compiler/register_allocation/ApplyAssignmentTest.java
(Actually, a solution that never requires a temporary register would be more complicated than I thought at first.)
=> Fix register allocator bugs from meeting

src/main/java/edu/kit/compiler/JavaEasyCompiler.java, src/main/java/edu/kit/compiler/OptimizationLevel.java
+ add constant optimization to optimization level 0
=> Change optimization flags to `O{0, 1}`

src/main/java/edu/kit/compiler/codegen/ExitCondition.java, src/main/java/edu/kit/compiler/codegen/InstructionSelection.java, src/main/java/edu/kit/compiler/codegen/PatternCollection.java, src/main/java/edu/kit/compiler/codegen/pattern/ConditionPattern.java, src/main/java/edu/kit/compiler/codegen/pattern/UnknownPattern.java
Note: Also includes some general cleanup in `InstructionSelection`.
=> Handle `Unknown` control flow in instruction selection

pom.xml, src/main/java/edu/kit/compiler/JavaEasyCompiler.java, src/main/java/edu/kit/compiler/optimizations/ArithmeticIdentitiesOptimization.java, src/main/java/edu/kit/compiler/optimizations/ArithmeticReplacementOptimization.java, src/main/java/edu/kit/compiler/optimizations/CallGraph.java, src/main/java/edu/kit/compiler/optimizations/ConstantOptimization.java, src/main/java/edu/kit/compiler/optimizations/Optimization.java, src/main/java/edu/kit/compiler/optimizations/Optimizer.java, src/test/java/edu/kit/compiler/optimizations/ArithmeticIdentitiesOptimizationTest.java, src/test/java/edu/kit/compiler/optimizations/ArithmeticReplacementOptimizationTest.java, src/test/java/edu/kit/compiler/optimizations/CallGraphTest.java
This PR introduces an interface for global optimizations (i.e. optimizations that work on the entire program instead of a single graph). A call graph is also implemented to query calling-realtionships between functions and to detect recursions.
=> Add call graph and global optimizations

src/main/java/edu/kit/compiler/JavaEasyCompiler.java, src/main/java/edu/kit/compiler/optimizations/LinearBlocksOptimization.java, src/test/java/edu/kit/compiler/optimizations/LinearBlocksOptimizationTest.java
See `LinearBlockVisitor::visit` for an explanation when blocks can be joined.
=> Add linear blocks optimization

src/main/java/edu/kit/compiler/optimizations/LinearBlocksOptimization.java, src/main/java/edu/kit/compiler/optimizations/LoopInvariantOptimization.java, src/main/java/edu/kit/compiler/optimizations/NodeCosts.java, src/main/java/edu/kit/compiler/optimizations/Util.java, src/main/java/edu/kit/compiler/optimizations/loop_invariant/MoveInvariantStrategies.java, src/test/java/edu/kit/compiler/optimizations/LoopInvariantOptimizationCallTest.java, src/test/java/edu/kit/compiler/optimizations/LoopInvariantOptimizationTest.java
+ correctly call `confirmProperties(NONE)` in `LinearBlocksOptimization`
=> Add `MinimizeRegisterPressure` strategy to `LoopInvariantOptimization`

src/main/java/edu/kit/compiler/optimizations/PureFunctionOptimization.java
Previously the `CallCollector` of the pure function optimization, would call the analysis to compute function attributes. This is problematic, as that analysis also modifies the `visited` flags of the Firm graph, which could lead to unpredictable behavior.
Note: _This is quite difficult to reproduce in practice, hence the lack of a corresponding test case._
=> Fix a bug in the `PureFunctionOptimization`

mjtest-files/exec/unusedArgs/AlternatingRecursive.mj, mjtest-files/exec/unusedArgs/Simple.mj, src/main/java/edu/kit/compiler/JavaEasyCompiler.java, src/main/java/edu/kit/compiler/optimizations/UnusedArgumentsOptimization.java, src/main/java/edu/kit/compiler/optimizations/Util.java, src/main/java/edu/kit/compiler/optimizations/analysis/UnusedArgumentsAnalysis.java
Finally, we get a global optimization :smile:
=> Add unused arguments optimization

mjtest-files/compile/bench/AbstractedMath.mj, mjtest-files/compile/bench/Knapsack.mj, mjtest-files/compile/bench/ProgrammingTutorial.mj, mjtest-files/compile/bench/SubsetSum.mj
This branch is intended to collect some ideas for benchmarks.
If you want to see a really huge difference between `-O1` and `-O0`, check out the `AbstractedMath` benchmark :smile:
=> Benchmarks
