larsk21/compiler-minijava

- build
- run_mjtests.sh
The CI should actually fail if there are failing tests (based on #35)
> Correct return code handling in scripts/CI

- src/main/java/edu/kit/compiler/data/DataType.java
- src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorSystem.java
Prevents using void method result where any type is allowed as argument.
```
void foo() { }
System.out.println(foo());
```
Prevents comparison of two void method results with variable type operators.
```
void foo() { }
foo() == foo();
```
> fix: Void type is not compatible to anything

- src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java
- src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorSystem.java
Before, the field was not defined, now it is forbidden to access it. Makes `System` field shadow stdlib in static methods as well.
> fix: field access is not allowed in static methods

- src/main/java/edu/kit/compiler/lexer/Lexer.java
- src/test/java/edu/kit/compiler/lexer/LexerTest.java
The new lexer introduced a bug, where closing comments delimiters would be ignored if they were preceded by an asterisk (as in `/***/`).
> Fix subtle bug in lexing of comments

- src/main/java/edu/kit/compiler/JavaEasyCompiler.java
- src/main/java/edu/kit/compiler/semantic/NamespaceMapper.java
- src/main/java/edu/kit/compiler/transform/Lower.java
- src/main/java/edu/kit/compiler/transform/TypeMapper.java
This is an initial implementation for converting MiniJava types to Firm types. It is supposed to serve as a starting point for further functionality, as it also generates method entities necessary to generate actual code graphs.
> Implement Firm type construction

- src/main/java/edu/kit/compiler/data/AstVisitor.java
- src/main/java/edu/kit/compiler/data/ast_nodes/ExpressionNode.java
- src/main/java/edu/kit/compiler/semantic/DefinitionKind.java
- src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java
- src/main/java/edu/kit/compiler/semantic/StandardLibrary.java
- src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorSystem.java
Standard library calls are now a special construct without `System` or `System.out`/`System.in` being defined on its own. The following code yields "`System` cannot be resolved":
```
// inside some method
if (System.out == null) {
...
```
detailed changes:
- remove global variable `System`
- change `StandardLibrary` to include only names and method definitions
- explicitly check method invocations to identify standard library calls
- allow removing the object of a method invocation
- add tests for standard library calls
> Remodel standard library

- src/main/java/edu/kit/compiler/transform/IRExpressionVisitor.java
- src/main/java/edu/kit/compiler/transform/IRStatementVisitor.java
Previously return statements with an expression would not use an old memory state.
> fix: Correctly set memory for return statements

- src/main/java/edu/kit/compiler/transform/Lower.java
`Backend.lowerForTarget` resolves only functionality we are not using. In addition it performs some optimizations which may conflict with the optimizations we have implemented.
> Remove unnecessary `lowerForTarget`

- mjtest-files/compile/Permutation.mj
- mjtest-files/compile/PermutationComplex.mj
- src/main/java/edu/kit/compiler/codegen/BasicBlocks.java
- src/main/java/edu/kit/compiler/codegen/ExitCondition.java
- src/main/java/edu/kit/compiler/codegen/InstructionSelection.java
- src/main/java/edu/kit/compiler/codegen/PermutationSolver.java
- src/main/java/edu/kit/compiler/codegen/PhiResolver.java
- src/main/java/edu/kit/compiler/codegen/ReversePostfixOrder.java
- src/main/java/edu/kit/compiler/intermediate_lang/Block.java
- src/test/java/edu/kit/compiler/codegen/PermutationSolverTest.java
- src/test/java/edu/kit/compiler/codegen/ReversePostfixOrderTest.java
Currently, the phi resolver interacts with the instruction selection in the following ways:
1. using the state of the instruction selection to create new virtual registers
2. using the state of the instruction selection to create new block ids
3. appending move instructions to some blocks
4. altering exit conditions when a new block is introduced
1 and 2 are probably unavoidable, 3 could also be done within the `PhiResolver` instead. However, while 4 could be done separately, it would be rather ugly to do so, as the `PhiResolver` would need to duplicate the exit condition mechanism of the instruction selection somehow.
Also, the block ids are now serialized.
> Phi resolver and block ordering

- .github/workflows/maven.yml
- mjtest-files/semantic/IndefiniteAssignment.valid.mj
- src/main/java/edu/kit/compiler/codegen/PatternCollection.java
- src/main/java/edu/kit/compiler/codegen/pattern/UnknownPattern.java
- src/main/java/edu/kit/compiler/transform/IRStatementVisitor.java
The instruction selection must be able to deal with `Unknown` nodes. `Unknown` nodes may for example result from using the value of a local variable prior to assignment. As the definite assignment rules of Java don't apply in MiniJava, our compiler must be able to generate code for such programs.
> Handle Unknown nodes during instruction selection

- src/main/java/edu/kit/compiler/JavaEasyCompiler.java
- src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java
- src/main/java/edu/kit/compiler/semantic/Reference.java
- src/test/java/edu/kit/compiler/optimizations/ConstantOptimizationTest.java
- src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorCorrectlyTypedTest.java
- src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorResultTypeTest.java
- src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorSystemTest.java
- src/test/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitorTest.java
- src/test/java/edu/kit/compiler/semantic/SemanticChecksTest.java
- src/test/java/edu/kit/compiler/transform/IRBooleanExpressionsTest.java
- src/test/java/edu/kit/compiler/transform/IRExpressionVisitorTest.java
- src/test/java/edu/kit/compiler/transform/IRPointerVisitorTest.java
- src/test/java/edu/kit/compiler/transform/IRStatementVisitorTest.java
- src/test/java/edu/kit/compiler/transform/IRVisitorTest.java
- src/test/java/edu/kit/compiler/transform/TypeMapperTest.java
closes #60 
fixed bugs:
- for a default binary expression with an incompatible type on the right side of the operator, the error message included the type of the expression on the left side
- if a method invocation had too many arguments, the nodes of the additional arguments were not visited
> Change detailed type analysis to use `ErrorHandler`

- src/main/java/edu/kit/compiler/optimizations/ArithmeticIdentitiesOptimization.java
- src/main/java/edu/kit/compiler/optimizations/ArithmeticReplacementOptimization.java
- src/test/java/edu/kit/compiler/optimizations/ArithmeticIdentitiesOptimizationTest.java
This PR implements two small transformations to the Firm graph. When combined these lead to better usage of addressing modes in certain situations. For example the following function will translate to something like `movl 16(%rsi,%rdx,4), %eax`.
```java
public int foo(int[] arr, int i) {
return arr[i + 4];
}
```
> Improve usage of addressing modes

- src/main/java/edu/kit/compiler/optimizations/ArithmeticIdentitiesOptimization.java
- src/main/java/edu/kit/compiler/transform/IRPointerVisitor.java
- src/test/java/edu/kit/compiler/optimizations/ArithmeticIdentitiesOptimizationTest.java
Negative indizes are undefined behavior in MiniJava. We can use this to avoid emitting an unnecessary `movslq`.
Note: This does not work if the conversion is propagated to operands, because operands on their own might still be negative.
> Assume that array indizes are always positive

- mjtest-files/compile/pattern/LoadEffective.java
- src/main/java/edu/kit/compiler/codegen/Operand.java
- src/main/java/edu/kit/compiler/codegen/PatternCollection.java
- src/main/java/edu/kit/compiler/codegen/pattern/LoadEffectivePattern.java
- src/main/java/edu/kit/compiler/codegen/pattern/OperandPattern.java
This PR adds functionality to allow for the use of load effective address during instruction selection. This just reuses the memory patterns used to match `Load` nodes. Most additions of registers, additions with constants, as well as a limited number of multiplications (those with 2, 4, or 8) can now be expressed using `lea`. 
Note: There is still room for improvement here. For example multiplications by 3, 5, and 9 could also be expressed using `lea`.
> Add `lea` pattern to instruction selection

- src/main/java/edu/kit/compiler/optimizations/PureFunctionOptimization.java
- src/test/java/edu/kit/compiler/optimizations/PureFunctionOptimizationTest.java
Previously, the tuples used to remove calls to constant functions would directly point to the call. This is wrong, as it omits the required projection to get the result tuple of the call.
> fix: Correctly replace const calls

- mjtest-files/compile/LifetimeError.mj
- mjtest-files/compile/LifetimeError2.mj
- src/main/java/edu/kit/compiler/codegen/ReversePostfixOrder.java
- src/main/java/edu/kit/compiler/intermediate_lang/Block.java
- src/main/java/edu/kit/compiler/register_allocation/LifetimeAnalysis.java
- src/test/java/edu/kit/compiler/codegen/ReversePostfixOrderTest.java
- src/test/java/edu/kit/compiler/register_allocation/LifetimeAnalysisTest.java
Previously, the lifetime analysis assumed that for nested loops, the blocks are ordered in a way such that the blocks of the outer loop enclose the blocks of the inner loop, thus allowing the lifetime analysis to find loops based on the back jump at the end of the loop.
However, this ordering is not always possible anymore with the linear blocks optimization, because there might be e.g. a direct jump from the header of the inner loop to the header of the outer loop.
Therefore, I have changed the lifetime analysis to use loop depths instead, which are set by the analysis done for the block ordering (`ReversePostfixOrder`). Additionally, `ReversePostfixOrder` must now ensure that the loop depths are "flat", i.e. there can be no hole with lower depth in a loop, which could be created e.g. by …
> Fix lifetime analysis regarding intermangled loops

- src/main/java/edu/kit/compiler/JavaEasyCompiler.java
- src/main/java/edu/kit/compiler/assembly/AssemblyOptimizer.java
- src/main/java/edu/kit/compiler/assembly/JumpInversion.java
- src/main/java/edu/kit/compiler/assembly/RemoveNop.java
- src/main/java/edu/kit/compiler/io/LookaheadIterator.java
- src/test/java/edu/kit/compiler/assembly/JumpInversionTest.java
This PR introduces a basic framework for assembly optimizations and uses it to implement the following two optimizations.
1. Jump Inversion (I don't know if that is the correct name) uses fall-through to optimize conditional jumps followed by unconditional ones where possible. For example, the following list of instruction
```asm
jnz .L1
jmp .L2
.L1:
```
is simplified to
```asm
jz .L2
.L1:
```
2. Remove all `nop`s, which may have been introduced to deal with `Unknown` nodes during instruction selection.
> Add assembly optimizations

- src/main/java/edu/kit/compiler/JavaEasyCompiler.java
- src/main/java/edu/kit/compiler/optimizations/LoopInvariantOptimization.java
- src/main/java/edu/kit/compiler/optimizations/Util.java
- src/main/java/edu/kit/compiler/optimizations/analysis/LoopAnalysis.java
- src/main/java/edu/kit/compiler/optimizations/analysis/LoopInvariantAnalysis.java
- src/main/java/edu/kit/compiler/optimizations/constant_folding/UndefinedCondStrategies.java
- src/main/java/edu/kit/compiler/optimizations/inlining/InliningOptimization.java
- src/main/java/edu/kit/compiler/optimizations/loop_invariant/MoveInvariantStrategies.java
- src/test/java/edu/kit/compiler/optimizations/LoopAnalysisTest.java
- src/test/java/edu/kit/compiler/optimizations/LoopInvariantOptimizationCallTest.java
- src/test/java/edu/kit/compiler/optimizations/LoopInvariantOptimizationTest.java
Adds an optimization that moves loop-invariant nodes in front of the loop (to the deepest common dominator of the loop entry point predecessors). In nested loops, nodes are moved out as far as possible. Currently, only data nodes are moved (except Phis), but const/pure (? @g4rgoil) functions could be added, if applicable.
> Add loop invariant optimization

- mjtest-files/compile/Knapsack.mj
- mjtest-files/compile/StackSlots.mj
- src/main/java/edu/kit/compiler/register_allocation/ApplyAssignment.java
- src/main/java/edu/kit/compiler/register_allocation/LifetimeAnalysis.java
- src/main/java/edu/kit/compiler/register_allocation/LinearScan.java
- src/main/java/edu/kit/compiler/transform/StandardLibraryEntities.java
- src/test/java/edu/kit/compiler/register_allocation/ApplyAssignmentTest.java
Adds two minor improvements to the register allocator:
- The allocator now only aligns the stack pointer to 16 byte if the call is a standard library call
- When spilling a register, the allocator is now able to reuse stack slots and also able to use the stack slot of a stack-passed argument. Further, the PR adds a small refinement to the heuristic for selecting the spilled register.
(Note: The second improvement applies quite seldomly, as we are rarely spilling registers anyway.)
> Minor register allocation improvements

- mjtest-files/semantic/UnresolvedVariable.invalid.java
- src/main/java/edu/kit/compiler/semantic/SemanticChecks.java
Fixes a bug, where a `NullPointerException` could occur during semantic checks, if an unresolved identifier was used in the main method of a program.
> Fix minor issue in semantic checks

- src/main/java/edu/kit/compiler/optimizations/inlining/InliningOptimization.java
- src/main/java/edu/kit/compiler/optimizations/inlining/InliningStateTracker.java
Makes the inliner much more likely to decide that a function is worth to be inlined (basically, only quite large functions with no constant argument will be rejected by the heuristic now). The limits for acceptable function size increase are also increased, but not by too much, thus the worst case compile time shouldn't be affected much.
> Adjust inlining heuristic

- src/main/java/edu/kit/compiler/register_allocation/ApplyAssignment.java
Fixes a bug where the register allocator assumed a value to be present that is actually overwritten.
> Fix issue in handling of temporary registers

- mjtest-files/exec/unroller/MultiplePhis.java
- src/main/java/edu/kit/compiler/optimizations/unrolling/LoopVariableAnalysis.java
Previously `Phi` nodes on any path of a loop variable would always result in a non-constant step value. This PR improves the handling of `Phi`s slightly, to allow for a limited number of cases to still detect a constant step value.
> Improve handling of Phis in loop variable analysis

- run_mjtests.sh
- src/main/java/edu/kit/compiler/register_allocation/ApplyAssignment.java
- src/main/java/edu/kit/compiler/register_allocation/LifetimeAnalysis.java
It was possible that the wrong loop depth was assigned to a vRegister and thus the lifetime not extended correctly with regard to other loops
> Fix nasty bug in register allocation/lifetime analysis

- mjtest-files/exec/PureFunctionTerminates.inf.java
- src/main/java/edu/kit/compiler/optimizations/PureFunctionOptimization.java
This bug was introduced as part of #161. The fix prevents the `while (true)` from _disappearing_ in the following snippet.
> ```java
> while (true) {
>     int j = 0;
>     while (j < 999 && j < 1000) {
>         j = j + 1;
>     }
> }
> ```
> Fix a regression in the pure function optimization

- mjtest-files/exec/PureFunctionTerminates.inf.java
- mjtest-files/exec/unroller/HeaderPhiConst.java
- mjtest-files/exec/unroller/PrematureReturn.java
- mjtest-files/exec/unroller/UnclosedLoop.java
- src/main/java/edu/kit/compiler/optimizations/PureFunctionOptimization.java
- src/main/java/edu/kit/compiler/optimizations/unrolling/LoopAnalysis.java
- src/main/java/edu/kit/compiler/optimizations/unrolling/LoopUnroller.java
- src/main/java/edu/kit/compiler/optimizations/unrolling/LoopUnrollingOptimization.java
- src/main/java/edu/kit/compiler/optimizations/unrolling/LoopVariableAnalysis.java
1. Fix a simple `NullPointerException` related to an incorrect assumption about `Phi`s in the loop header.
2. Only try to unroll _closed_ loops, i.e. loops that don't contain jumps that leave the loop in their body.
These fixes fully resolve the following two issues found in the review.
> - Falsche Ausgabe mit -O1
> ```java
> class test {
>     public static void main(String[] args) {
>         System.out.println(new test().hindex());
>     }
>     
>     public int hindex() {
>         int i = 0;
>                 int[] help = new int[2];
>         help[0] = 0;
>         help[1] = 0;
>                 i=0;
>         while (i <= 1) {
>             if (i>help[i]) return i-1;
>             i=i+1;
>         }
>         return 999;
>     }       
> }
> ```
>  - (Simon_164, Simon_165, licm)
> …
> Fix issues related to loop unrolling

- mjtest-files/exec/unusedArgs/AlphabeticalRegisterTransfer.java
- src/main/java/edu/kit/compiler/optimizations/analysis/UnusedArgumentsAnalysis.java
`UnusedArgumentsAnalysis` would run into a stack overflow, if an argument to a non-inlined function was part of a loop in that functions graph.
> Fix endless recursion in unused args analysis

- mjtest-files/compile/RegAllocUpcastSize.mj
- src/main/java/edu/kit/compiler/register_allocation/ApplyAssignment.java
I think this is our first bug that primarily affects `-O0` (happens only for an unsigned upcast to a register that is spilled)
> Fix for target size in case of upcast to stack slot
